version: '3.8'
services:
    postgres:
        build: ./Postgres
        restart: always
        volumes:
          - postgres-data:/var/lib/postgresql/data # persist data even if container shuts down
        ports:
          - "5433:5432"
        environment:  
          POSTGRES_USER_FILE: /run/secrets/postgres_root_username
          POSTGRES_PASSWORD_FILE: /run/secrets/postgres_root_password
          POSTGRES_OTHER_USER_FILE: /run/secrets/postgres_username
          POSTGRES_OTHER_PASS_FILE: /run/secrets/postgres_password
          POSTGRES_DB: jobscheduled
        networks:
          - backend
        secrets:
          - postgres_password
          - postgres_username
          - postgres_root_password
          - postgres_root_username
    mongodb:
        build: ./Mongo
        restart: always
        volumes:
          - mongodb-data:/data/db # persist data even if container shuts down
        environment:
          MONGO_INITDB_DATABASE: Admin
          MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
          MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
          MONGO_DATABASE: emotionsMap
          MONGO_USERNAME_FILE: /run/secrets/mongodb_username
          MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
        ports:
          - "64015:27017"
        networks:
          - backend
        secrets:
        - mongodb_root_username
        - mongodb_root_password
        - mongodb_username
        - mongodb_password
    administration-app:
        build: backend/administration_app/central_system
        restart: always
        networks:
          - backend
          - frontend
        ports:
          - "7082:7080"
        depends_on:
          - postgres
          - mongodb
volumes:
    postgres-data:
    mongodb-data:
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
secrets:
    mongodb_root_username:
        file: Mongo/secrets/mongodb_root_username
    mongodb_root_password:
        file: Mongo/secrets/mongodb_root_password
    mongodb_username:
        file: Mongo/secrets/mongodb_username
    mongodb_password:
        file: Mongo/secrets/mongodb_password
    postgres_root_username:
        file: Postgres/Secrets/postgres_root_username
    postgres_root_password:
        file: Postgres/Secrets/postgres_root_password
    postgres_username:
        file: Postgres/Secrets/postgres_username
    postgres_password:
        file: Postgres/Secrets/postgres_password
    
        
    
